apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: decode # The name of the app
  namespace: default # The namespace the app will use
spec:
  template:
    spec:
      containers:
        - image: harbor.test.com/knative/decode-caseless:v4
          env:
            - name: PAY_SERVICE # The environment variable printed out by the sample app
              value: "http://pay.default.serverless.dds-sysu.tech"
