apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: image-recognition
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/yuxiaoba/image-recognition:v1
